name: Auto Approve
description: Automatically approve pull requests
branding:
  icon: check-circle
  color: green
inputs:
  github_token:
    description: GitHub API Access Token
    required: true
  message:
    description: Approval message
    required: true
    default: '[AUTO-APPROVED]'
runs:
  using: docker
  image: Dockerfile
